name: Run Tests

on:
  push:
    branches:
      - "**"
    branches-ignore:
      - gh-pages
    paths-ignore: 
      - "playground/**"
  pull_request:
    branches:
      - "**"
    branches-ignore:
      - gh-pages
    paths-ignore: 
      - "playground/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
